src/main/java/com/razorpay/OrderClient.java

Adding fetchAll() method in OrderClient

OrderClient

---

src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/Invoice.java
src/main/java/com/razorpay/InvoiceClient.java
src/main/java/com/razorpay/RazorpayClient.java

- Create Invoice
- Get Invoice by Id
- List all invoices

Invoice API

---

src/main/java/com/razorpay/ApiUtils.java

Set okhttp client timeout to 60 seconds

---

pom.xml

[Version]: Upgrading the version

---

src/main/java/com/razorpay/PaymentClient.java
src/main/java/com/razorpay/TransferClient.java

- fetchAllTransfers for Payments
- fetchAll Transfers

[Transfers]: Adding default fetch methods for transfers

---

pom.xml

[Change Log]
- Modified the Utility class to verify webhook signature using the secret provided.

[Version Upgrade]: Version upgrade to 1.3.1

---

README.md
pom.xml
src/main/java/com/razorpay/Addon.java
src/main/java/com/razorpay/AddonClient.java
src/main/java/com/razorpay/ApiClient.java
src/main/java/com/razorpay/ApiUtils.java
src/main/java/com/razorpay/BankTransfer.java
src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/PaymentClient.java
src/main/java/com/razorpay/Plan.java
src/main/java/com/razorpay/PlanClient.java
src/main/java/com/razorpay/RazorpayClient.java
src/main/java/com/razorpay/Subscription.java
src/main/java/com/razorpay/SubscriptionClient.java
src/main/java/com/razorpay/VirtualAccount.java
src/main/java/com/razorpay/VirtualAccountClient.java

Edit operations added whereever applicable. Also checked that the new APIs have access under `private`

New apis for Subscription, Addon, Plan, Virtual Account and bank transfer

---

pom.xml

[Change Log]: Support for Subscription, Addon, Plan, Virtual Account and Bank Transfer

[Version Upgrade]: Version upgrade to 1.3.2

---

README.md
src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/CustomerClient.java

Support for Deleting Customer Token

api added for card deletion

---

src/main/java/com/razorpay/AddonClient.java
src/main/java/com/razorpay/ApiClient.java
src/main/java/com/razorpay/CustomerClient.java

In case of delete we do not get entity name, which is used to create an obj of that entity.
Since delete is mainly void return type, we throw an exception if the status is non 200.

[Token]: Fixing token delete call

---

src/main/java/com/razorpay/ApiClient.java
src/main/java/com/razorpay/Entity.java

- Add helper methods to Entity
- Make delete public in ApiClient

Minor improvements

---

pom.xml
src/main/java/com/razorpay/ApiUtils.java

Ref: https://github.com/square/okhttp/wiki/HTTPS

[TLS]: Adding support for TLS 1.2

---

README.md
pom.xml
src/main/java/com/razorpay/ApiUtils.java
src/main/java/com/razorpay/CustomTLSSocketFactory.java

Ref: https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-javax.net.ssl.X509TrustManager-

[TLS]: Support for TLSv1.2

---

pom.xml
src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/VirtualAccountClient.java

* Added new endpoint for close VA
* updates VA close method

[B2BAPP-53] close VA SDK update

---

README.md
pom.xml

Updated pom with mvn source compiler version

---

documents/refund.md

[Create a normal refund ](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A50): [update](https://github.com/razorpay/razorpay-java/blob/refunds_doc_correction/documents/refund.md?plain=1#L17)
[Create an instant refund](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A51) :  [update](https://github.com/razorpay/razorpay-java/blob/refunds_doc_correction/documents/refund.md?plain=1#L62)
[Fetch all refunds for a payment](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A52) : [update](https://github.com/razorpay/razorpay-java/blob/refunds_doc_correction/documents/refund.md?plain=1#L106)
[Fetch a specific refund for a …

refunds doc correction

---

documents/subscription.md
src/main/java/com/razorpay/SubscriptionClient.java

[Create a subscription (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A75) : `import java.util.ArrayList;`
[create a subscription link (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A76) : `import java.util.ArrayList;`
[Fetch subscription link by id](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A78) : use [fetch](https://github.com/razorpay/razorpay-java/blob/subscription_doc_correction/documents/subscription.md?plain=1#L218) method
[cancel subscription link (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A79) : 
use …

subscription doc correction

---

documents/addon.md
src/main/java/com/razorpay/AddonClient.java

[Fetch all addon (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A94) : according to java sdk structure it show inside items array not
[Delete an addon (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A96) : [update](https://github.com/razorpay/razorpay-java/blob/subscription_doc_correction/documents/subscription.md?plain=1#L694)

addon doc correction

---

documents/item.md

[Create an item (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A99): [update](https://github.com/razorpay/razorpay-go/blob/item_doc_correction/documents/item.md?plain=1#L24)
[fetch an item  (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A100): [update](https://github.com/razorpay/razorpay-java/blob/item_doc_correction/documents/item.md?plain=1#L108)
[Fetch multiple item (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A101) : [update](https://github.com/razorpay/razorpay-java/blob/item_doc_correction/documents/item.md?plain=1#L66)
[Update an item  (sdk …

item doc correction

---

documents/paymentLink.md

Create a standard payment link (sdk audit) : update
[Create a UPI payment link (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A107) : [update](https://github.com/razorpay/razorpay-java/blob/paymentlink_doc_correction/documents/paymentLink.md?plain=1#L63)
[Update a Payment link (sdk audit) ](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A108): [update](https://github.com/razorpay/razorpay-java/blob/paymentlink_doc_correction/documents/paymentLink.md?plain=1#L141)
[Transfer payments received using payment links (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A113) : `amount` is mandatory and add `import …

paymentlink doc correction

---

documents/virtualAccount.md

[Create virtual account (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A126) : add `import java.util.ArrayList;` , [update](https://github.com/razorpay/razorpay-go/blob/smartcollect_doc_correction/documents/virtualAccount.md?plain=1#L28)
[Fetch payment for an virtual account (sdk audit) ](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A129): [update](https://github.com/razorpay/razorpay-java/blob/smartcollect_doc_collection/documents/virtualAccount.md?plain=1#L295)
[Fetch payment details using id and transfer method (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A130) : …

Smartcollect doc collection

---

documents/transfer.md

Create transfer from order and payment : add `import java.util.ArrayList;`
[Direct transfer (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A141) : [update](https://github.com/razorpay/razorpay-java/blob/transfer_doc_correction/documents/transfer.md?plain=1#L170)
[Fetch a transfer for payment (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A142) : [update](https://github.com/razorpay/razorpay-java/blob/transfer_doc_correction/documents/transfer.md?plain=1#L198)
Fetch Transfer for an order (sdk audit) : [update](https://github.com/razorpay/razorpay-java/blob/transfer_doc_correction/documents/transfer.md?plain=1#L236)
[Fetch Transfer (sdk …

transfer doc correction

---

documents/card.md

[Create an registration link (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A181) : [update](https://github.com/razorpay/razorpay-java/blob/card_doc_correction/documents/card.md?plain=1#L140)
[cancel registration link (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A183) : [update](https://github.com/razorpay/razorpay-java/blob/card_doc_correction/documents/card.md?plain=1#L360)
[Fetch token by payment id](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A184) : [update](https://github.com/razorpay/razorpay-java/blob/card_doc_correction/documents/card.md?plain=1#L433)
[Fetch token by customer …

card doc correction

---

documents/registerNach.md

[Create order ](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A233) : [update](https://github.com/razorpay/razorpay-java/blob/registernach_doc_correction/documents/registerNach.md?plain=1#L92)
[Create registration link](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A235) : [update](https://github.com/razorpay/razorpay-java/blob/registernach_doc_correction/documents/registerNach.md?plain=1#L206)
[Create an order to charge customer](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A240) : [update](https://github.com/razorpay/razorpay-java/blob/registernach_doc_correction/documents/registerNach.md?plain=1#L332)

registernach doc correction

---

documents/token.md

Doc reference : https://razorpay.com/docs/payments/third-party-validation/s2s-integration/upi/collect#step-22-fetch-vpa-tokens-of-a-customer

added tpv token

---

documents/payment.md
src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/Methods.java
src/main/java/com/razorpay/PaymentClient.java
src/test/java/com/razorpay/PaymentClientTest.java

Doc reference : https://razorpay.com/docs/payments/third-party-validation/s2s-integration/netbanking#step-3-create-a-payment

added tpv payment

---

README.md
documents/addon.md
documents/card.md
documents/emandate.md
documents/fund.md
documents/invoice.md
documents/item.md
documents/order.md
documents/papernach.md
documents/payment.md
documents/paymentLink.md
documents/plan.md
documents/refund.md
documents/registerEmandate.md
documents/registerNach.md
documents/settlement.md
documents/subscription.md
documents/token.md
documents/transfer.md
documents/upi.md
documents/virtualAccount.md
pom.xml
src/main/java/com/razorpay/AddonClient.java
src/main/java/com/razorpay/Constants.java
src/main/java/com/razorpay/FundAccountClient.java
src/main/java/com/razorpay/Methods.java
src/main/java/com/razorpay/PaymentClient.java
src/main/java/com/razorpay/SubscriptionClient.java
src/test/java/com/razorpay/PaymentClientTest.java

[Create an order (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A9) : It will create automatically if you have offer for that amount or else you will null in `offers`
[Fetch all offer (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A10) : 
It will create automatically if you have offer for that amount or else you will null in `offers`
[Fetch an order with id (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A11) : the sequence of response is changing because of json object 
`{
"amount": 50000,
"amount_paid": 0,
"notes": {
"notes_key_1": "Tea, Earl Grey, Hot"
},
"created_at": 1656913369, …

order doc correction

---

src/main/java/com/razorpay/QrCodeClient.java
src/test/java/com/razorpay/QrCodeClientTest.java

Api reference : https://razorpay.com/docs/api/qr-codes

qrcode entity and mock

---

src/main/java/com/razorpay/PaymentLinkClient.java
src/test/java/com/razorpay/PaymentLinkTest.java

Api reference : https://razorpay.com/docs/api/payment-links/

Paymentlink entity nmock

---

src/main/java/com/razorpay/VirtualAccountClient.java
src/test/java/com/razorpay/VirtualAccountClientTest.java

Api reference : https://razorpay.com/docs/api/payments/smart-collect

virtualaccount entity and mock

---

src/main/java/com/razorpay/AddonClient.java
src/test/java/com/razorpay/AddonClientTest.java

Api reference : https://razorpay.com/docs/api/payments/subscriptions/#add-on

addon entity and mock

---

src/main/java/com/razorpay/PlanClient.java
src/test/java/com/razorpay/PlanClientTest.java

Api reference : https://razorpay.com/docs/api/payments/subscriptions/#plans

plan entity and mock

---

src/main/java/com/razorpay/RefundClient.java
src/test/java/com/razorpay/RefundClientTest.java

Api reference : https://razorpay.com/docs/api/refunds

Refund entity nmock

---

src/main/java/com/razorpay/PaymentClient.java
src/test/java/com/razorpay/PaymentClientTest.java

API reference : https://razorpay.com/docs/api/payments

Payment entity nmock

---

src/main/java/com/razorpay/SettlementClient.java
src/test/java/com/razorpay/SettlementClientTest.java

Api reference : https://razorpay.com/docs/api/settlements/

settlement entity and mock

---

src/main/java/com/razorpay/CardClient.java
src/test/java/com/razorpay/CardClientTest.java

Api reference : https://github.com/razorpay/razorpay-java/blob/master/src/main/java/com/razorpay/CardClient.java

card entity and mock

---

src/main/java/com/razorpay/ItemClient.java
src/test/java/com/razorpay/ItemClientTest.java

Api reference : https://razorpay.com/docs/api/payments/items

Item entity nmock

---

src/main/java/com/razorpay/CustomerClient.java
src/test/java/com/razorpay/CustomerClientTest.java

Api reference for customer : https://razorpay.com/docs/api/customers

customer entity and mocktest

---

src/main/java/com/razorpay/InvoiceClient.java
src/test/java/com/razorpay/InvoiceClientTest.java

API reference : https://razorpay.com/docs/api/payments/invoices

Invoice entity nmock

---

pom.xml

| Test Case Document URL                        |
|-----------------------------------------------|
| Please paste test case document link here.... |

increase codecoverage

---

documents/payment.md
src/main/java/com/razorpay/PaymentClient.java
src/test/java/com/razorpay/PaymentClientTest.java

Api doc reference
[Fetch a Payment (With Expanded Card Details)](https://razorpay.com/docs/api/payments/fetch-payment-expanded-card/)
[Fetch a Payment (With Expanded EMI Details)](https://razorpay.com/docs/api/payments/fetch-payment-expanded-emi/)
[Fetch a Payment (With Expanded Offers Details)](https://razorpay.com/docs/api/payments/fetch-payment-expanded-offers/)
[Fetch a Payment (With Expanded UPI Details)](https://razorpay.com/docs/api/payments/fetch-payment-expanded-upi/)

added expanded details methods

---

.github/workflows/ci.yml
pom.xml

| Test Case Document URL                        |
|-----------------------------------------------|
| Please paste test case document link here.... |

[CEPF-1677] Updated Json package version to fix security vulnerabilities

---

CHANGELOG.md
README.md

Fix: Updated json dependency to fix security vulnerability

Version bump v1.4.7

---

CHANGELOG.md
README.md
pom.xml

| Test Case Document URL                        |
|-----------------------------------------------|
| Please paste test case document link here.... |

bump version v1.4.8
